export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Dashboard } from './Dashboard';
export { default as QuizHome } from './QuizHome';
export { default as QuizCreation } from './QuizCreation';
export { default as Profile } from './Profile';
export { default as QuizCreationBasic } from './QuizCreationBasic';
export { default as QuizPlay } from './QuizPlay';
export { default as Leaderboard } from './Leaderboard';
